---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - name: test
      image: busybox:latest
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: mypvc
          mountPath: /volume
  volumes:
    - name: mypvc
      persistentVolumeClaim:
        claimName: test-pvc
        readOnly: false
